{% set name = "pyfda" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyfda-{{ version }}.tar.gz
  sha256: b713549802d26b22b39ea38c9a3cad0b58ec78c063a7ce08093fe893ec2e6d72
  patches:
    - 0001-Only-install-the-pyfda-package-and-not-any-extra-dir.patch

build:
  entry_points:
    - pyfdax = pyfda.pyfdax:main
    - pyfdax_no_term = pyfda.pyfdax:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pyqt
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy >=1.2.0
    - matplotlib-base >=3.3
    - docutils
    - mplcursors
    - numexpr >=2.8.8
    - markdown
    - pyqt

test:
  imports:
    - pyfda
  commands:
    # ignore pip check while upstream requires numpy < 2 but it works anyway
    #- pip check
    - pyfdax -h
    - pyfdax_no_term -h
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/chipmuenk/pyFDA
  summary: Python filter design analysis tool
  license: MIT
  license_file: LICENSE.md
  description: >
    pyfda is a tool written in Python / Qt for analyzing and designing discrete time filters with a user-friendly GUI. Fixpoint filter implementations (for some filter types) can be simulated and tested for overflow and quantization behaviour in the time and frequency domain.

extra:
  recipe-maintainers:
    - ryanvolz
