{% set name = "pyfda" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyfda-{{ version }}.tar.gz
  sha256: b6fb7f95e9c4fd8f73354a98bd467bf26deb1f120ef0259246ac4c11b04f2a69
  patches:
    - 0001-Only-install-the-pyfda-package-and-not-any-extra-dir.patch

build:
  entry_points:
    - pyfdax = pyfda.pyfdax:main
    - pyfdax_no_term = pyfda.pyfdax:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pyqt
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy >=1.2.0
    - matplotlib-base >=2.1
    - docutils
    - mplcursors
    - numexpr <=2.8.4
    - markdown
    - pyqt

test:
  imports:
    - pyfda
  commands:
    - pip check
    - pyfdax -h
    - pyfdax_no_term -h
  requires:
    - pip

about:
  home: https://github.com/chipmuenk/pyFDA
  summary: Python filter design analysis tool
  license: MIT
  license_file: LICENSE.md
  description: >
    pyfda is a tool written in Python / Qt for analyzing and designing discrete time filters with a user-friendly GUI. Fixpoint filter implementations (for some filter types) can be simulated and tested for overflow and quantization behaviour in the time and frequency domain.

extra:
  recipe-maintainers:
    - ryanvolz
